export const stringHelper = {
  welcome: 'Awesome Workout',
  emptyList: 'Please Add at least  "one area"',
  emptyIntensity: 'Please Select Intensity',
  weightCompare: 'Target weight must be lower than weight',
  dayWorkout: 'Please select workout days',
  inputDialogHint: 'Type Here',
  cancel: 'Cancel',
  createBut: 'Create',
  cancelBut: 'Cancel',
  deleteBut: 'Delete',
  editBut: 'Edit',
  submit: 'Submit',
  next: 'Next',
  set: 'Set',
  save: 'Save',
  back: 'Back',
  tryLater: 'Try Later!',
  screens: {
    Workout: 'Workout',
    profile: 'Profile',
    mainStack: 'Main',
    authStack: 'Auth',
    tabNavigator: 'TabNavigator',
    settingNavigator: 'SettingNavigator',
    // AUTH SCREENS
    splash: 'Splash',
    login: 'Login',
    signup: 'Sign Up',
    forgetPassword: 'Forget password',
    workout: 'Workout',
    area: 'Area',
    intensity: 'Intensity',
    timerComponent: 'Timer',
    workoutDays: 'WorkoutDays',
    editProfile: 'EditProfile',
    history: 'Workout History',
    detailHistory: 'Workout Detail',
  },
  icons: {
    sessionA: 'people-circle-outline',
    sessionB: 'person-circle-sharp',
    arrowRight: 'right',
    circleThin: 'circle-thin',
    checkCircle: 'check-circle',
    add: 'Add',
    search: 'Search',
    addCircle: 'Add-Circle',
    reminder: 'Reminder',
    remove: 'remove',
    microphone: 'microphone',
    arrowInput: 'Arrow-Right',
    trash: 'Delete-Fill',
    return: 'Back',
  },
  profile:{
    editProfile: 'Edit profile',
    firstName: 'firstName',
    lastName: 'LastName',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    targetWeight: 'TargetWeight',
    numberType: 'Please enter number for ',
    updatedProfile: 'Profile Updated Successfully ',
  },
  auth: {
    checkInbox: 'Check Your Inbox',
    resetPassword: 'Reset password',
    forgetPasswordSentence:
      'If you don’t know your current password, you may change it. Please make sure this is the same email that you have used to sign up before.',
    checkInboxSentenceOne:
      'If you have signed up before using this email, we just sent an email to:\n',
    checkInboxSentenceTwo:
      ' Open it and tap the Change Password link to continue.\n\n Please allow up to 10 minutes for the email to arrive.',
    hasAccount: 'Already have an account',
    loginHere: 'Login here',
    login: 'Login',
    authRule1: 'By continuing, you agree that you accept our  ',
    authRule2: ' and ',
    signup: 'Sign up',
    password: 'Password',
    choosePassword: 'Choose Password',
    email: 'Email',
    firstName: 'First Name (or Nickname)',
    emailRepeat: 'Email (again please)',
    forgetPassword: 'Forget password',
    emailInvalid: 'Invalid Email.',
    emailOrPasswordInvalid: 'Your Email or Password is incorrect.',
    emailRepeatInvalid: 'Please make sure both emails are exactly the same.',
    passwordLength: 'Password length is short.',
    passwordRepeateInvalid: 'Repeat Wrong Password.',
    fillData: 'Please Fill All Data.',
    checkEmail:'Check your Inbox & reset password',
    conectionErr: 'Can not connect to server, try later.',
    logoutConfirm: 'Are you sure you want to log out?\n',
    logoutConfirmTitle: 'Log out Confirmation',
    logout: 'Log Out',
  },
  queryMessages: {
    create: {
      successful: 'Document(s) successfully created.',
      exists: 'Document(s) exists.',
    },
    get: {
      found: 'Document(s) successfully fetched.',
      notFound: 'Document(s) not found.',
    },
    update: {
      successful: (documentId = '') => `${documentId} successfully updated.`,
      notExists: (documentId = '') =>
        `"${documentId}" has been deleted or does not exists.`,
    },
    delete: {
      successful: (documentId = '') => `${documentId} successfully deleted.`,
      notExists: (documentId = '') =>
        `"${documentId}" has been deleted or does not exists.`,
    },
  },
};
